---
- name: Install virt-manager
  become: yes
  apt:
    update_cache: yes
    name:
      - virt-manager
      - libguestfs-tools
      - genisoimage
      - python3-pip
      - libvirt-dev
      - python3-lxml
