---
- name: Install virt-manager
  become: yes
  apt:
    update_cache: yes
    name:
      - virt-manager
      - libguestfs-tools
      - genisoimage
      - python3-pip

- name: Install libvirt pip packages
  become: yes
  community.general.pipx:
    name:
      - libvirt-python
      - lxml
