---
- name: Fetch the latest Kubebuilder tags from GitHub
  uri:
    url: "https://api.github.com/repos/kubernetes-sigs/kubebuilder/tags"
    return_content: yes
  register: github_response
  changed_when: false

- name: Extract the latest Kubebuilder version from the API response
  set_fact:
    kubebuilder_version: "{{ github_response.json | json_query('[0].name') | regex_replace('^v', '') }}"

- name: Download kubebuilder {{ kubebuilder_version }}
  become: yes
  get_url:
    url : https://github.com/kubernetes-sigs/kubebuilder/releases/download/v{{ kubebuilder_version }}/kubebuilder_linux_amd64
    dest: /usr/local/bin/kubebuilder
    mode: '+x'
