---
- name: Download Microsoft GPG Key
  get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /tmp/microsoft.asc

- name: Add Microsoft GPG Key
  command: gpg
    --yes
    --dearmor
    --output /etc/apt/trusted.gpg.d/microsoft.gpg
    /tmp/microsoft.asc

- name: Delete Microsoft GPG Key - tmp file
  file:
    path: /tmp/microsoft.asc
    state: absent

- name: Add Microsoft repository
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release }} main
