---
- name: Install prerequisites
  become: yes
  apt:
    update_cache: yes
    name:
      - apt-transport-https
      - zsh
      - vim
      - python3-pip
      - bpytop
      - htop
      - ripgrep
      - iftop
      - curl
      - telegram-desktop
      - bless
      - vlc
      - wireguard-tools
      - resolvconf
      - simplescreenrecorder
      - tree
      - gimp
      - zip
      - unzip
      - rar
      - unrar
      - gnome-tweaks
