---
- name: Download Tor Browser
  become: yes
  unarchive:
    src: https://dist.torproject.org/torbrowser/{{ tor_browser_version }}/tor-browser-linux64-{{ tor_browser_version }}_ALL.tar.xz
    dest: /opt
    remote_src: yes

- name: Change owner to {{ ansible_user_id }}
  become: yes
  file:
    path: /opt/tor-browser
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    state: directory
    recurse: yes
