---
- name: Download Tor Browser {{ tor_browser_version }}
  become: yes
  unarchive:
    src: https://archive.torproject.org/tor-package-archive/torbrowser/{{ tor_browser_version }}/tor-browser-linux64-{{ tor_browser_version }}_ALL.tar.xz
    dest: /opt
    remote_src: yes

- name: Change owner to {{ ansible_user_id }}
  become: yes
  file:
    path: /opt/tor-browser
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    state: directory
    recurse: yes

- name: Copy Tor browser desktop icon
  become: yes
  copy:
    src: start-tor-browser.desktop
    dest: /usr/share/applications/start-tor-browser.desktop
