---
- name: Download kubecolor {{ kubecolor_version }}
  unarchive:
    src: https://github.com/hidetatz/kubecolor/releases/download/v{{ kubecolor_version }}/kubecolor_{{ kubecolor_version }}_Linux_{{ ansible_architecture }}.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy kubecolor to executable path
  become: yes
  copy:
    src: /tmp/kubecolor
    dest: /usr/local/bin/kubecolor
    mode: '+x'
