---
- name: Download aws cli tool
  unarchive:
    src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp
    remote_src: yes

- name: Install aws cli tool
  become: yes
  command: /tmp/aws/install
