---
- name: Install Hashicorp tools
  apt:
    update_cache: yes
    name:
      - terraform
      - vault
      - vagrant
      - packer

- name: Install Vagrant plugins
  command: vagrant plugin install {{ item }}
  with_items:
    - vagrant-vbguest
    - vagrant-scp
