---
- name: Add OBS Studio repo
  become: yes
  apt_repository:
    repo: ppa:obsproject/obs-studio

- name: Install OBS Studio
  become: yes
  apt:
    update_cache: yes
    name:
      - obs-studio
      - ffmpeg
