---
- name: Install VirtualBox {{ virtualbox_version }}
  apt:
    update_cache: yes
    name:
      - virtualbox-{{ virtualbox_version }}
      - virtualbox-guest-utils

- name: Create VirtualBox config directory
  file:
    path: /etc/vbox
    state: directory

- name: Copy VirtualBox network config file
  copy:
    src: networks.conf
    dest: /etc/vbox/networks.conf

- name: Add user to vboxusers group
  user:
    name: "{{ ansible_user_id }}"
    groups: vboxusers
    append: yes
