---
- name: Install Sublime Text
  apt:
    update_cache: yes
    name: sublime-text

- name: Create Sublime Text config directory
  file:
    path: "{{ ansible_user_dir }}/.config/sublime-text/Packages/User"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    state: directory

- name: Copy Sublime Text config
  copy:
    src: Preferences.sublime-settings
    dest: "{{ ansible_user_dir }}/.config/sublime-text/Packages/User/Preferences.sublime-settings"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0664
