---
- name: Install Sublime Text
  apt:
    update_cache: yes
    name: sublime-text

- name: Copy Sublime Text Configs
  copy:
    src: Preferences.sublime-settings
    dest: "{{ ansible_user_dir }}/.config/sublime-text/Packages/User/Preferences.sublime-settings"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0644
