---
- name: Install Sublime Text
  apt:
    update_cache: yes
    name: sublime-text

- name: Create Sublime Text config directories
  file:
    path: "{{ ansible_user_dir }}/.config/sublime-text/{{ item }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    state: directory
  with_items:
    - Packages/User
    - Local
    - Lib
    - Log
    - "Installed Packages"

- name: Copy Sublime Text config
  copy:
    src: Preferences.sublime-settings
    dest: "{{ ansible_user_dir }}/.config/sublime-text/Packages/User/Preferences.sublime-settings"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: 0664
