---
- name: Install IBM Cloud CLI tool
  become: yes
  shell: |
    curl -fsSL https://clis.cloud.ibm.com/install/linux | sh

- name: Install IBM Cloud CLI plugins
  command: ibmcloud plugin install container-service -f
