---
- name: Install libvirt
  apt:
    update_cache: yes
    name:
      - virt-manager
      - libguestfs-tools
      - genisoimage

- name: Install libvirt pip packages
  pip:
    name:
      - libvirt-python
      - lxml
