---
- name: Install Light Display Manager
  apt:
    update_cache: yes
    name: lightdm

- name: Configure Light Display Manager
  debconf:
    name: gdm3
    question: shared/default-x-display-manager
    vtype: string
    value: lightdm

- name: Create a symbolic link for Display Manager
  file:
    src: /lib/systemd/system/lightdm.service
    dest: /etc/systemd/system/display-manager.service
    state: link

-  name: Update X11 default display manager
   copy:
    content: "/usr/sbin/lightdm"
    dest: "/etc/X11/default-display-manager"

# - name: Activate LightDM configs
#   command: dpkg-reconfigure -f noninteractive gdm3

# - name: Disable GNOME Display Manager
#   service:
#     name: gdm
#     enabled: no

- name: Copy lock on wakeup service for lightdm
  copy:
    src: lock-on-wakeup.service
    dest: /etc/systemd/system/lock-on-wakeup.service

- name: Enable lock on wakeup service
  service:
    name: lock-on-wakeup
    enabled: yes
