---
- name: Install LightDM
  apt:
    update_cache: yes
    name: lightdm

- name: Configure LightDM
  debconf:
    name: gdm3
    question: shared/default-x-display-manager
    vtype: string
    value: lightdm

- name: Activate LightDM configs
  command: dpkg-reconfigure -f noninteractive gdm3

- name: Copy lock on wakeup service for lightdm
  copy:
    src: lock-on-wakeup.service
    dest: /etc/systemd/system/lock-on-wakeup.service

- name: Enable lock on wakeup service
  service:
    name: lock-on-wakeup
    enabled: yes
