---
- name: Fetch the latest Etcher tags from GitHub
  uri:
    url: "https://api.github.com/repos/balena-io/etcher/tags"
    return_content: yes
  register: github_response
  changed_when: false

- name: Extract the latest Etcher version from the API response
  set_fact:
    etcher_version: "{{ github_response.json | json_query('[0].name') | regex_replace('^v', '') }}"

- name: Install Etcher {{ etcher_version }}
  become: yes
  apt:
    deb: https://github.com/balena-io/etcher/releases/download/v{{ etcher_version }}/balena-etcher_{{ etcher_version }}_amd64.deb
