---
- name: Fetch the latest RKE tags from GitHub
  uri:
    url: "https://api.github.com/repos/rancher/rke/tags"
    return_content: yes
  register: github_response
  changed_when: false

- name: Extract the latest RKE version from the API response
  set_fact:
    rke_version: "{{ github_response.json | json_query('[0].name') }}"

- name: Download rke {{ rke_version }}
  become: yes
  get_url:
    url: https://github.com/rancher/rke/releases/download/{{ rke_version }}/rke_linux-amd64
    dest: /usr/local/bin/rke
    mode: '+x'
